### ISSUE TITLE
Consider including Pramda

### ISSUE THREAD

**Issue by kapolos** [marcelgsantos/getting-started-with-fp-in-php#1]
Hi,

Please consider adding [Pramda](https://github.com/kapolos/pramda) to the Library list.

Thank you!

**Comment by marcelgsantos** [comment]
Pramda was included in Pull Request #2.
By the way, Pramda is an awesome library. ;)

Congratulations!

Marcel dos Santos

**Comment by kapolos** [comment]
Thank you very much! I'm very happy to hear you like it :beers:
